### PR TITLE
Update README.md with support of WHMCS v8.x

### PR DESCRIPTION
**Pull request by LilianCr**
The module has been fully tested on WHMCS v8.x

### CODE REVIEW

**Comment by angel9215** [comment]
Hi, thank you for your commit, before accepting it I'd like to know what benefits it has over WHMCS default name servers setting (you can find in admin it under Setup > General settings > Domains)
This is the API call used when the name servers are changed there:
https://sandbox.namesilo.com/api/registerDomain?version=1&type=xml&key=***********************&domain=test234324.com&years=1&payment_id=736&coupon=&private=&ns1=ns1.hostsilo.com&ns2=ns2.hostsilo.com&ns3=&ns4=&ns5=&fn=test&ln=client&ad=add+1&ad2=&cy=cty&st=AK&zp=55000&ct=US&em=test%40example.com&ph=2056665555&auto_renew=0

I used ns1.hostsilo.com and ns2.hostsilo.com as the custom name servers

I don't really see any difference or reason to specify the name servers on the module, and I'd prefer this option since it's part of WHMCS itself

Also thanks a lot for checking compatibility with 8.x, I checked the changelog and didn't see anything that could conflict with the module but didn't run the tests yet

**Comment by LilianCr** [comment]
Hi Angel ! I have specify the nameservers on the module cause I had defined nameservers in Setup > General settings > Domains, but when a customer has bought a domain, the namesilo's default nameservers was applied :slightly_smiling_face:

**Comment by angel9215** [comment]
Maybe there was some problem with the name servers, on this test the name servers were changed. Some TLDs/registries set the default name servers when there is a problem, others simply get stuck

**Comment by LilianCr** [comment]
I don't know, but by this way, it works perfectly and it was just what I needed. So I shared my update with you but it was only a proposal, if you are not interested, you can always refuse it :)

**Comment by angel9215** [comment]
I guess I'll reject this for now, also I'll create a new branch for 8.0, I found some issues, I'll check compatibility with this there

**Pull request closed without merging**
